variables:
  libplistBuild: 53
jobs:
- job: windows
  strategy:
    matrix:
      x64:
        BUILD_ARCH: x64
        PLATFORM: x64
        RID: win7-x64
      x86:
        BUILD_ARCH: x86
        PLATFORM: Win32
        RID: win7-x86
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: |
      git clone https://github.com/microsoft/vcpkg
      vcpkg\bootstrap-vcpkg.bat
    displayName: Install vcpkg
  - script: |
      vcpkg\vcpkg version
      vcpkg\vcpkg integrate install
      set VCPKG_BUILD_TYPE=release
      vcpkg\vcpkg install libplist:%BUILD_ARCH%-windows --head
    displayName: Install libplist
  - task: MSBuild@1
    inputs:
      solution: 'libusbmuxd.sln' 
      platform: $(PLATFORM)
      configuration: Release
    displayName: 'Release build'
  - task: MSBuild@1
    inputs:
      solution: 'libusbmuxd.sln' 
      platform: $(PLATFORM)
      configuration: Debug
    displayName: 'Debug build'

- job: macos
  pool:
    vmImage: 'xcode9-macos10.13'
  variables:
    TARGET: x86_64-apple-darwin
    RID: osx-x64
  steps:
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'specific'
      project: 'imobiledevice-net'
      pipeline: '2'
      buildVersionToDownload: 'specific'
      buildId: $(libplistBuild)
      downloadType: 'single'
      artifactName: 'drop'
      downloadPath: '$(System.ArtifactsDirectory)'
    displayName: 'Download libplist artifacts'
  - script: |
      brew install autoconf automake libtool pkg-config
    displayName: Install autotools
  - script: |
      ls $SYSTEM_ARTIFACTSDIRECTORY/drop/$RID/
      export CFLAGS="$CFLAGS -I$SYSTEM_ARTIFACTSDIRECTORY/drop/$RID/include"
      export PKG_CONFIG_PATH="$SYSTEM_ARTIFACTSDIRECTORY/drop/$RID/lib/pkgconfig:$PKG_CONFIG_PATH"
      export LDFLAGS="$LDFLAGS -L$SYSTEM_ARTIFACTSDIRECTORY/drop/$RID/lib"
      ./autogen.sh --prefix=$BUILD_ARTIFACTSTAGINGDIRECTORY/$RID --host=$TARGET --enable-static=yes --enable-shared=no
      make
    displayName: Build
  - script: |
      make install
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
      artifactName: 'drop' 
      publishLocation: 'Container'
    displayName: Publish

- job: linux
  variables:
    TARGET: x86_64-unknown-linux-gnu
    RID: ubuntu.16.04-x64
    CFLAGS: -fPIC
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'specific'
      project: 'imobiledevice-net'
      pipeline: '2'
      buildVersionToDownload: 'specific'
      buildId: $(libplistBuild)
      downloadType: 'single'
      artifactName: 'drop'
      downloadPath: '$(System.ArtifactsDirectory)'
    displayName: 'Download libplist artifacts'
  - script: |
      ls $SYSTEM_ARTIFACTSDIRECTORY/drop/$RID/
      export CFLAGS="$CFLAGS -I$SYSTEM_ARTIFACTSDIRECTORY/drop/$RID/include"
      export PKG_CONFIG_PATH="$SYSTEM_ARTIFACTSDIRECTORY/drop/$RID/lib/pkgconfig:$PKG_CONFIG_PATH"
      export LDFLAGS="$LDFLAGS -L$SYSTEM_ARTIFACTSDIRECTORY/drop/$RID/lib"
      ./autogen.sh --prefix=$BUILD_ARTIFACTSTAGINGDIRECTORY/$RID --host=$TARGET --enable-static=yes --enable-shared=no
      make
    displayName: Build
  - script: |
      make install
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
      artifactName: 'drop' 
      publishLocation: 'Container'
    displayName: Publish